name: "deploy"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to server
        uses: dokku/github-action@master
        with:
          branch: "main"
          git_remote_url: "${{ secrets.GIT_REMOTE_URL }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
